[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
preDeployCommand = "npx prisma db push --skip-generate"
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
