[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate"

[deploy]
preDeployCommand = "npx prisma db push --skip-generate"
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
